### ISSUE TITLE
No styling for admin page

### ISSUE THREAD

**Issue by niklasvatn** [datasektionen/verksamt#11]
The styling for the admin page is not working. 

Maybe this could fix it. https://www.pythonanywhere.com/forums/topic/1252/

![image](https://user-images.githubusercontent.com/55627591/109195564-f8563400-779a-11eb-9cce-a291fe17beff.png)

**Comment by bullfest** [comment]
Probably something broken with collectstatic or serving of static files

**Comment by bullfest** [comment]
I can take a look at it over the weekend

**Comment by ViklasN** [comment]
Great!
It has been like this for at least a year now FYI, the last commit didn't cause the error.
